// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/doffy007/banking-api/pkg/core/v1/user/controller"
	"github.com/doffy007/banking-api/pkg/core/v1/user/resource"
	"github.com/doffy007/banking-api/pkg/core/v1/user/service"
)

// Injectors from wire.go:

func UserControllerV1() *controller.UserController {
	interfaceUserResource := resource.InitUserResource()
	interfaceUserService := service.InitUserService(interfaceUserResource)
	userController := controller.InitUserController(interfaceUserService)
	return userController
}
